IN_GBP = ['amazon', 'natwest', 'rbs', 'mands', 'amex', 'lloyds', 'firstdirect']
IN_EUR = ['ing', 'bankia', 'bankia1']


PENSIONS = {'Óscar': [40000, [('Contribución empresa', 0.10), ('Contribución personal', 0.10)]],
            'Maika': [40000, [('Contribución empresa', 0.10), ('Contribución personal', 0.10)]]
            }

SALARY_DEDUCTIONS = {'Óscar': ['2020-01-01', ['Recibos', 'Seguro médico', 'GHD Bupa Private health care', 100]]
                     }

INPUT_FOLDER = 'input'
OUTPUT_FOLDER = 'output'

COLUMNS_RENAMING = {
    'amazon'      : {'amount(gbp)': 'amount'},
    'natwest'     : {'value': 'amount'},
    'rbs'         : {'value': 'amount'},
    'mands'       : {'merchant/description': 'description', 'debit/credit': 'amount'},
    'bankia'      : {'fec.valor': 'date', 'descripcion': 'description', 'importe': 'amount', 'div.': 'currency',
                     'datevalue': 'date', 'description': 'description', 'amount': 'amount'},
    'ing'         : {'f.valor': 'date', 'descripción': 'description', 'importe(€)': 'amount'},
    'lloyds'      : {'transactiondate': 'date', 'transactiondescription': 'description'},
    'amex'        : {},
    'firstdirect' : {} 
    }

RECORDS_TO_DROP = {
    'description': ['payment received', 'american express' , 'initial payment'
                    'fp', 'amazon cards', 'club lloyds', 'traspaso interno recibido',
                    'cargo cuota anual', 'annual fee', 'devolucion cuota anual', 
                    'to a/c 12345392', 'to a/c 12345384', 'to a/c 12345861', 'to a/c 12345239',
                    'from a/c 12345392', 'from a/c 12345384', 'from a/c 12345861', 'from a/c 12345239',
                    'm carmen rodrigo m', 'mariacarmen rodrig',
                    'g-costa', 'garcia-cos o', 'garcia costa', 'garcia-costa', 'garcia cos o',
                    'maria-lloyds' , 'pago', 'natwest', 'ingreso cajero',
                    'to reward account', 'from oscar mands', 'from rbs',
                    'sent from revolut', 'drs overfund'
                   ],
    'type' :       ['c/l', 'payment', 'so', 'atm'
                   ] 
    }
                    
DESCRIPTION_DIC = {
    'type' :        {'int': ['Otros ingresos', 'Intereses', 'Intereses']},
    'description' : {
                    '\'o2': ['Recibos', 'Móvil', 'O2 Óscar'],
                    'a/c 12345541': ['Varios', 'Comisiones', 'Comisión RBS'],
                    'a/c 12345861': ['Varios', 'Comisiones', 'Comisión Natwest Rewards'],
                    'aingels': ['Bares', '', 'Comer en Angels'],
                    'airbnb': ['Turismo', '', 'AirBnB'],
                    'aldi': ['Groceries', 'Discount shops', 'Aldi'],
                    'amazon prime': ['Recibos', 'Subscriptions', 'Amazon Prime'],
                    'amznmktplace': ['', '', 'Amazon'],
                    'atalian servest gr salisbury': ['Bares', 'Trabajo', 'Café en el trabajo'],
                    'apollo hotel':['Ocio', '', 'Hotel Apollo BSK'],
                    'asda': ['Groceries', 'ASDA', 'ASDA'],
                    'aviva': ['Recibos', 'Seguros', 'Seguro de vida y enfermedad'],
                    'b and m': ['Groceries', 'Discount shops', 'B&M'],
                    'b&m': ['Groceries', 'Discount shops', 'B&M'],
                    'barclays uk mtges': ['Alojamiento', 'Hipoteca', 'Hipoteca Barclays'],
                    'basingstoke and dean': ['Alojamiento', 'Council tax', 'Council tax Basingstoke'],
                    'basingstoke hwrc': ['Cosas casa', '', 'Tirar escombro'],
                    'basingstoke sports': ['Ocio', 'Actividades Emma', 'Piscina Emma'],
                    'basingstoke wellness': ['Varios', 'Estética', 'Basingstoke Wellness tratamiento cara'],
                    'boots': ['', '', 'Boots'],
                    'carrefour': ['Groceries', 'Carrefour', 'Carrefour'],
                    'charter': ['Groceries', 'Consum', 'Charter'],
                    'chineham arms': ['Bares', '', 'Chinenham Arms'],
                    'claire\'s accessories': ['Ropa y complementos', '', 'Claire\'s'],
                    'clinica dental dt': ['Varios', 'Salud', 'Dentista Vero'],
                    'consum': ['Groceries', 'Consum', 'Consum'],
                    'debenhams ': ['', '', 'Debenhams '],
                    'e.on': ['Gastos casa', 'Luz y gas', 'E.On'],
                    'easyjet': ['Transporte', '', 'Vuelos Easyjet'],
                    'eposnow':['Bares', '', 'Gabardine'],
                    'farmacia serigo quiles': ['Otras compras', 'Farmacia', 'Farmacia Pedralba'],
                    'festival street kitchen basingstoke' : ['Bares', 'Comer', 'Festival Street Chicken'],
                    'fgv': ['Transporte', 'Otros', 'Metro Valencia'],
                    'first cust contact': ['Otros ingresos', 'SWR', 'Devolución SWR'],
                    'gabardine bar': ['Bares', '', 'Gabardine BSK'],
                    'genei': ['Varios', 'Mudanzas', 'Envio de caja con Genei'],
                    'giardino': ['Bares', '', 'Tomar algo en Cafe Giardino'],
                    'giffgaff' : ['Recibos', 'Móvil', 'Giffgaff'],
                    'google play' : ['Recibos', 'Subscripciones', 'Subscripción Medium'],
                    'grantleys': ['Coche', '', 'Arreglar coche en Grantleys'],
                    'green network': ['Gastos Casa', 'Luz y gas', 'Green Network Energy'],
                    'greggs': ['Bares', '', 'Greggs'],
                    'h & m': ['Ropa y complementos', '', 'H&M'],
                    'h&m': ['Ropa y complementos', '', 'H&M'],
                    'h and m': ['Ropa y complementos', '', 'H&M'],
                    'hampshire hospitals nh':['Coche', 'Parking', 'Parking Hospital Basingstoke'],
                    'home bargains': ['Groceries','Discount shops', 'Home Bargains'],
                    'hobbycraft': ['Baby', 'Manualidades', 'Hobby craft'],
                    'holiday extras': ['Transporte', 'España', 'Parking aeropuerto'],
                    'homebase': ['Cosas casa', '', 'Homebase'],
                    'hxpayments': ['Transporte', 'España', 'Parking aeropuerto'],
                    'iceland' : ['Groceries', 'Other', 'Iceland'],
                    'interest': ['Otros ingresos', 'Intereses', 'Intereses Lloyds'],
                    'intereses': ['Otros ingresos', 'Intereses', 'Intereses ING/Bankia'],
                    'jessops': ['Otras compras', 'Fotos', 'Jessops'],
                    'lidl' : ['Groceries', 'Lidl', 'Lidl'],
                    'lime leaf': ['Bares', '', 'The Lime Leaf'],
                    'londis':['Groceries', 'Proximity shops', 'Londis'],
                    'lookfantastic': ['Otras compras', 'Cosmética', 'Look fantastic Skin care'],
                    'marks and spencer': ['', '', 'Marks & Spencer'],
                    'marks & spencer': ['', '', 'Marks & Spencer'],
                    'mercadona': ['Groceries', 'Mercadona', 'Mercadona'],
                    'millstone':['Bares', '', 'Burtons Mill'],
                    'morrisons petrol': ['Coche', 'Gasolina', 'Gasolina en Morrisons'],
                    'morrisons store' : ['Groceries', 'Morrisons', 'Morrisons'],
                    'movement stratagie': ['Nóminas', 'Óscar', 'Nómina de Óscar'],
                    'myrewards': ['Otros ingresos', 'Cashback', 'My Rewards Natwest'],
                    'netflix.com': ['Recibos', 'Subscriptiones', 'Netflix' ],
                    'next retail': ['Ropa y complementos', '', 'Next'],
                    'oddbox': ['Groceries', 'Other', 'Oddbox'],
                    'patisserie valerie': ['Bares', 'Cafetería', 'Pastisserie Valerie'],
                    'polski sklep smaczek': ['Groceries', 'Proximity shops', 'Tienda polaca'],
                    'poundland': ['', '', 'Poundland'],
                    'poundstretcher': ['Groceries', 'Discount shops', 'Poundstrecher'],
                    'primark': ['Ropa y complementos', '', 'Primark'],
                    'queen elizabeth countr': ['Turismo', 'De día', 'Queen Elizabeth Country Park'],
                    'river island': ['Ropa y complementos', '', 'River Island'],
                    'ryanair': ['Transporte', '', 'Vuelo Ryanair'],
                    's4k franchising':['Ocio', 'Actividades Emma', 'Rugby S4K'],
                    'sainsbury': ['Groceries', 'Sainsburys', 'Sainsburys'],
                    'sainsburys' : ['Groceries', 'Sainsburys', 'Sainsburys'],
                    'savers health' : ['Groceries', 'Discount shops', 'Savers'],
                    'schuh': ['Ropa y complementos', '', 'Schuh'],
                    'screwfix': ['Cosas casa', '', 'Screwfix'],
                    'simyo': ['Recibos', 'Móvil', 'Simyo'],
                    'slater menswear':['Ropa y complementos', 'Óscar', 'Camisas y trajes Slater'],
                    'smarty' : ['Recibos', 'Móvil', 'Móvil Óscar Smarty'],
                    'smyths toys' : ['', '', 'Smyth Toys'],
                    'snapfish': ['Otras compras', 'Fotos', 'Fotos Snapfish'],
                    'sora lucia': ['Bares', 'Cenar', 'Sora Lucia take away'],
                    'south east water': ['Gastos casa', 'Agua', 'South East Water'],
                    'spices and spi basin': ['Bares', '', 'Spices and Spirits'],
                    'spices and spirit basin': ['Bares', '', 'Spices and Spirits'],
                    'swrailway': ['Transporte', '', 'Billete de tren'],
                    't k maxx': ['', '', 'TkMaxx'],
                    'teagether basingstoke': ['Bares', '', 'Teagether'],
                    'tesco' : ['Groceries', 'Tesco', 'Tesco'],
                    'the dragonfly': ['Bares', '', 'The Dragonfly Basingstoke'],
                    'the holly blue': ['Bares', '', 'The Holly Blue BSK (Beggarwoods)'],
                    'the orchard commun': ['Bares', '', 'The Orchard Community Centre'],
                    'the parlour tea rooms': ['Bares', '', 'The Parlour Tea Rooms'],
                    'the range': ['', '', 'The Range'],
                    'tk maxx': ['', '', 'TK Maxx'],
                    'vanguard': ['Inversiones', '', 'Vanguard'],
                    'vinted': ['Ropa y complementos', '', 'Vinted'],
                    'virgin media':['Recibos', 'Internet', 'Virgin Media'],
                    'vodafone ltd': ['Recibos', 'Internet', 'Internet Vodafone'],
                    'vueling airlines': ['Transporte', '', 'Vuelos Vueling'],
                    'w h smith': ['','', 'WHSmith'],
                    'waitrose': ['Groceries', 'Other', 'Waitrose'],
                    'wickes' : ['Cosas casa', '', 'Wickes'],
                    'wilko': ['', '', 'Wilko'],
                    }
    }